CREATE TABLE Utenti
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE, --Indica che il nome è univoco, e non può essercene un altro uguale (Anche se per un utente con ID diverso) [è un vincolo di integrità]--
    cognome VARCHAR(256),
    password VARCHAR(256), --Devo assicurarmi che NON sia nulla--
    confermaPassword VARCHAR(256),
    frasePresentazione VARCHAR(256),
    dataNascita VARCHAR(256),
    urlFotoProfilo VARCHAR(256),
    username VARCHAR(256)    
);

CREATE TABLE Gruppi
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomeGruppo VARCHAR(256) UNIQUE --Indica che il nome è univoco, e non può essercene un altro uguale (Anche se per un utente con ID diverso) [è un vincolo di integrità]--
);

CREATE TABLE Post
(
    idPost INTEGER GEN	ERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore VARCHAR(256) UNIQUE, --Indica che il nome è univoco, e non può essercene un altro uguale (Anche se per un utente con ID diverso) [è un vincolo di integrità]--
    contenuto VARCHAR(256),
    urlPost VARCHAR(256), --Devo assicurarmi che NON sia nulla--
    tipo INTEGER
);


INSERT INTO Utenti (id, nome, cognome, password, confermaPassword, frasePresentazione, dataNascita, urlFotoProfilo, username)
VALUES (default, 
		'Mario',
		'Rossi',
		'123',
		'123',
		'I was once known as Jumpman',
		'1981-07-09',
		'/ProgettoAMM/Assets/marioRossi.jpg',
		'MMMR',
		1);
		
INSERT INTO Utenti (id, nome, cognome, password, confermaPassword, frasePresentazione, dataNascita, urlFotoProfilo, username)
VALUES (default, 
		'Luca',
		'Verdi',
		'123',
		'123',
		'I am a hero!',
		'1986-02-21',
		'/ProgettoAMM/Assets/lucaVerdi.jpg',
		'LLV',
		2);
		
INSERT INTO Utenti (id, nome, cognome, password, confermaPassword, frasePresentazione, dataNascita, urlFotoProfilo, username)
VALUES (default, 
		'Carlo',
		'Neri',
		'123',
		'123',
		'Nobody remembers me..',
		'1988-10-09',
		'/ProgettoAMM/Assets/carloRossi.gif',
		'CSGR',
		3);
		

INSERT INTO Post (idPost, autore, contenuto, urlPost, tipo)
VALUES (default,
		)